module.exports =
    {
        "data": {
            "commentTotal": 40,
            "comments": [
                {
                    "adminId": null,
                    "contentText": "喜欢就关注我",
                    "createTime": 1560158823647,
                    "device": "",
                    "displayName": "智酷方程式",
                    "headPortrait": "../../images/a.jpg",
                    "id": "",
                    "likeTotal": 2,
                    "replyContents": [{
                        "adminId": null,
                        "contentText": "@智酷方程式  一起进步",
                        "createTime": 1560158986524,
                        "device": "",
                        "displayName": "小明同学",
                        "headPortrait": "../../images/c.jpg",
                        "id": "",
                        "likeTotal": 2,
                        "replyContents": [],
                        "replyId": "sdf",
                    },
                    {
                        "adminId": null,
                        "contentText": "@智酷方程式： 威武，学习学习",
                        "createTime": 1560407232814,
                        "device": "",
                        "displayName": "神秘的前端开发",
                        "headPortrait": "../../images/b.jpg",
                        "id": "",
                        "likeTotal": 0,
                        "replyContents": [],
                        "replyId": "sdf",
                    }
                    ],
                    "replyId": "",
                },
                {
                    "adminId": null,
                    "contentText": "回复评论测试",
                    "createTime": 1559181043248,
                    "device": "",
                    "displayName": "小程序开发者",
                    "headPortrait": "../../images/a.jpg",
                    "id": "6688744",
                    "likeTotal": 2,
                    "replyContents": [
                        {
                            "adminId": null,
                            "contentText": "喜欢就回复我",
                            "createTime": 1559637575556,
                            "device": "",
                            "displayName": "神秘的前端开发",
                            "headPortrait": "../../images/b.jpg",
                            "id": "",
                            "likeTotal": 2,
                            "replyContents": [],
                            "replyId": "6688744",
                        },
                        {
                            "adminId": null,
                            "contentText": "@小程序开发者  和我们一起学",
                            "createTime": 1559729810894,
                            "device": "",
                            "displayName": "智酷方程式",
                            "headPortrait": "../../images/a.jpg",
                            "id": "",
                            "likeTotal": 2,
                            "replyContents": [],
                            "replyId": "6688744",
                        },
                        {
                            "adminId": null,
                            "contentText": "@小程序开发者  技术永无止境",
                            "createTime": 1559731014839,
                            "device": "",
                            "displayName": "智酷方程式",
                            "headPortrait": "../../images/a.jpg",
                            "id": "",
                            "likeTotal": 2,
                            "replyContents": [],
                            "replyId": "6688744",
                        },
                        {
                            "adminId": null,
                            "contentText": "@神秘的前端开发  加油加油！",
                            "createTime": 1559731267002,
                            "device": "",
                            "displayName": "智酷方程式",
                            "headPortrait": "../../images/a.jpg",
                            "id": "",
                            "likeTotal": 2,
                            "replyContents": [],
                            "replyId": "6688744",
                        },
                        {
                            "adminId": null,
                            "contentText": "@智酷方程式  😂😂😂😂😂",
                            "createTime": 1560158083857,
                            "device": "",
                            "displayName": "神秘的前端开发",
                            "headPortrait": "../../images/b.jpg",
                            "id": "",
                            "likeTotal": 1,
                            "replyContents": [],
                            "replyId": "6688744",
                        }
                    ],
                    "replyId": "",
                }
            ],
            "curPage": 1,
            "likes": [
                "123",
                "333",
                "6688744",
            ],
            "nextPage": null,
            "pageSize": 20,
            "prePage": null,
            "queryTotal": 7,
            "total": 7,
            "totalPage": 1
        },
        "msg": "success",
        "status": "success"
    }